title: Satyaki Basak
logo: /assets/img/Satyaki_basak_image.png
description: "Economics & Data Science Enthusiast | Data Science | Quantitative Finance"
show_downloads: false
theme: jekyll-theme-minimal

