title: Satyaki Basak
logo: /assets/img/Satyaki_basak_image.png
description: "Economics & Data Science Enthusiast | Data Science | Quantitative Finance"
show_downloads: false
theme: jekyll-theme-minimal
email: satyakibasak01@gmail.com
linkedin: https://www.linkedin.com/in/satyakibasak
github: https://github.com/SatyakiB-ops
